<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon;

class UsersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
      $now = Carbon::now();
        DB::table('users')->insert([
            [
            'user' => 'superadmin',
            'name' => 'Superadmin',
            'last_name' => null,
            'dni' => null,
            'description' => 'I am the superuser. I have no limitations. Don\'t use me on production.',
            'email' => 'admin@admin.com',
            'password' => bcrypt('superadmin'),
            'created_at' => $now,
            'updated_at' => $now,
            'last_password_change' => $now,
            'phone' => null,
            'address' => null,
            ],
            ['user' => 'admin',
            'name' => 'Administrator',
            'last_name' => null,
            'dni'  => null,
            'description' => 'I am the main administration account. Use me when you need to administrate the app.',
            'email' => 'devilu@admin.com',
            'password' => bcrypt('admin'),
            'created_at' => $now,
            'updated_at' => $now,
            'last_password_change' => $now,
            'phone' => null,
            'address' => null,
            ],
            ['user' => 'manager',
            'name' => 'Manager',
            'last_name' => null,
            'dni' => null,
            'description' => 'I am the manager of the app. Use me on a regular basis.',
            'email' => 'user@admin.com',
            'password' => bcrypt('manager'),
            'created_at' => $now,
            'updated_at' => $now,
            'last_password_change' => $now,
            'phone' => null,
            'address' => null,
            ],
            ['user' => 'user',
            'name' => 'User',
            'last_name' => null,
            'dni' => '18486501',
            'description' => 'I am the default user. Grant me no special permissions.',
            'email' => 'user@admin.com',
            'password' => bcrypt('user'),
            'created_at' => $now,
            'updated_at' => $now,
            'last_password_change' => $now,
            'phone' => '0212-861.12.68',
            'address' => 'Av. Sucre de Catia, resd. "El Metro", Torre "B", piso 23, Caracas-Venezuela',
            ],
            ['user' => 'ventanilla',
            'name' => 'Ventanilla',
            'last_name' => null,
            'dni' => null,
            'description' => '',
            'email' => 'ventanilla@admin.com',
            'password' => bcrypt('ventanilla'),
            'created_at' => $now,
            'updated_at' => $now,
            'last_password_change' => $now,
            'phone' => null,
            'address' => null,
            ],
            ['user' => 'registrador',
            'name' => 'Registrador',
            'last_name' => null,
            'dni' => null,
            'description' => '',
            'email' => 'registrador@admin.com',
            'password' => bcrypt('registrador'),
            'created_at' => $now,
            'updated_at' => $now,
            'last_password_change' => $now,
            'phone' => null,
            'address' => null,
            ],
            ['user' => 'user1',
            'name' => 'User 1',
            'last_name' => null,
            'dni' => '194876087',
            'description' => 'I am the default user. Grant me no special permissions.',
            'email' => 'user@admin.com',
            'password' => bcrypt('user'),
            'created_at' => $now,
            'updated_at' => $now,
            'last_password_change' => $now,
            'phone' => '0212-861.12.68',
            'address' => 'Av. Sucre de Catia, resd. "El Metro", Torre "B", piso 23, Caracas-Venezuela',
            ],
            ['user' => 'user2',
            'name' => 'User 2',
            'last_name' => null,
            'dni' => '19756609',
            'description' => 'I am the default user. Grant me no special permissions.',
            'email' => 'user@admin.com',
            'password' => bcrypt('user'),
            'created_at' => $now,
            'updated_at' => $now,
            'last_password_change' => $now,
            'phone' => '0212-861.12.68',
            'address' => 'Av. Sucre de Catia, resd. "El Metro", Torre "B", piso 23, Caracas-Venezuela',
            ],
            ['user' => 'user3',
            'name' => 'User 3',
            'last_name' => null,
            'dni' => '1957607',
            'description' => 'I am the default user. Grant me no special permissions.',
            'email' => 'user@admin.com',
            'password' => bcrypt('user'),
            'created_at' => $now,
            'updated_at' => $now,
            'last_password_change' => $now,
            'phone' => '0212-861.12.68',
            'address' => 'Av. Sucre de Catia, resd. "El Metro", Torre "B", piso 23, Caracas-Venezuela',
            ],
            ['user' => 'user4',
            'name' => 'User 4',
            'last_name' => null,
            'dni' => '186876927',
            'description' => 'I am the default user. Grant me no special permissions.',
            'email' => 'user@admin.com',
            'password' => bcrypt('user'),
            'created_at' => $now,
            'updated_at' => $now,
            'last_password_change' => $now,
            'phone' => '0212-861.12.68',
            'address' => 'Av. Sucre de Catia, resd. "El Metro", Torre "B", piso 23, Caracas-Venezuela',
            ],
            ['user' => 'user5',
            'name' => 'User 5',
            'last_name' => null,
            'dni' => '19258650',
            'description' => 'I am the default user. Grant me no special permissions.',
            'email' => 'user@admin.com',
            'password' => bcrypt('user'),
            'created_at' => $now,
            'updated_at' => $now,
            'last_password_change' => $now,
            'phone' => '0212-861.12.68',
            'address' => 'Av. Sucre de Catia, resd. "El Metro", Torre "B", piso 23, Caracas-Venezuela',
            ],
        ]);
    }
}